[tool.poetry]
name = "goretsky-integration__database"
version = "1.0.0"
description = ""
authors = ["usbtypec1 <eldos.baktybekov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
psycopg2-binary = "^2.9.5"
djangorestframework = "^3.14.0"
django-environ = "^0.10.0"
django-import-export = "^3.1.0"
sentry-sdk = "^1.19.1"
httpx = "^0.24.0"
bs4 = "^0.0.1"
lxml = "^4.9.2"

[tool.poetry.group.dev.dependencies]
django-silk = "^5.0.3"
pytest-django = "^4.5.2"
pytest-cov = "^4.0.0"
pytest-httpx = "^0.22.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "goretsky_integration.settings"
python_files = "tests.py test_*.py *_tests.py"
